POST http://localhost:8080/api/register/begin
Content-Type: application/json

{
  "username": "doe",
  "displayName": "doe"
}

###

POST http://localhost:8080/api/register/finish?username=doe
Content-Type: application/json

{
  "id": "tJQilVIxmWzLZ_5o1944Ul90aFIpqCdb8vE",
  "rawId": "tJQilVIxmWzLZ_5o1944Ul90aFIpqCdb8vE",
  "type": "public-key",
  "response": {
    "attestationObject": "o2NmbXRkbm9uZWdhdHRTdG10oGhhdXRoRGF0YVieSZYN5YgOjGh0NBcPZHZgW4_krrmihjLHmVzzuoMdl2NdAAAAALraVWanqkAfvZZFYZpVEg0AGrSUIpVSMZlsy2f-aNfeOFJfdGhSKagnW_LxpQECAyYgASFYIE2YrvyMvZ0WxM9Cvhroh5pkO2kgxAm2grcgXlGUoNYeIlggheZcFg-tjVWqFVoeaGtLXKL3KoNW-J4JBmnbHEIwhLc",
    "clientDataJSON": "eyJ0eXBlIjoid2ViYXV0aG4uY3JlYXRlIiwiY2hhbGxlbmdlIjoiRTJMeTRwdXNpRUFuVzc5eXhwbm5kRGQxeGREYVJNc3RmNm52N3NkUEV3YyIsIm9yaWdpbiI6Imh0dHA6Ly9sb2NhbGhvc3Q6NjMzNDIiLCJjcm9zc09yaWdpbiI6ZmFsc2V9"
  }
}