POST localhost:8085/api/register/begin
Content-Type: application/json

{
  "username": "doe",
  "displayName": "doe"
}

###

POST localhost:8085/api/register/finish?username=doe
Content-Type: application/json

{
  "id": "0uIVEy_sww0-sKoMnu_8pOYt7QZ2YEb4blo7yuV36AbEM6hJZsq_j-cVloW_qaQUnPi0mgIfEgk68NNq",
  "rawId": "0uIVEy_sww0-sKoMnu_8pOYt7QZ2YEb4blo7yuV36AbEM6hJZsq_j-cVloW_qaQUnPi0mgIfEgk68NNq",
  "type": "public-key",
  "response": {
    "attestationObject": "o2NmbXRkbm9uZWdhdHRTdG10oGhhdXRoRGF0YVjASZYN5YgOjGh0NBcPZHZgW4_krrmihjLHmVzzuoMdl2NdAAAAALraVWanqkAfvZZFYZpVEg0APNLiFRMv7MMNPrCqDJ7v_KTmLe0GdmBG-G5aO8rld-gGxDOoSWbKv4_nFZaFv6mkFJz4tJoCHxIJOvDTaqUBAgMmIAEhWCDA5m_-takuyIeWH2W5v69j3bp0Ujj8nBQv59_MpkJ5XiJYIHxewQkLgFBdDYLTSmab7auyqYenZ7SeQy-icDrgUxjY",
    "clientDataJSON": "eyJ0eXBlIjoid2ViYXV0aG4uY3JlYXRlIiwiY2hhbGxlbmdlIjoiTDA3Ym5YT0tIdkp3SHFHbnhNYnR3dEF3dXJ0cVVXSkh1Z29BdXhPbkl2RSIsIm9yaWdpbiI6Imh0dHA6Ly9sb2NhbGhvc3Q6NjMzNDIiLCJjcm9zc09yaWdpbiI6ZmFsc2V9"
  }
}

###

POST localhost:8085/api/authenticate/begin
Content-Type: application/json

{
  "username": "doe"
}

###

POST localhost:8085/api/authenticate/finish?username=doe
Content-Type: application/json

{
  "id": "r4FMmWCZF2IYn8_xjv9mqVQRP3oiBGZ1jGpqnTPItFLTeZzWh9ET_DqcjrmCKjcGkyFJ2usIdalRGy9Onw",
  "rawId": "r4FMmWCZF2IYn8_xjv9mqVQRP3oiBGZ1jGpqnTPItFLTeZzWh9ET_DqcjrmCKjcGkyFJ2usIdalRGy9Onw",
  "type": "public-key",
  "response": {
    "authenticatorData": "SZYN5YgOjGh0NBcPZHZgW4_krrmihjLHmVzzuoMdl2MdAAAAAA",
    "clientDataJSON": "eyJ0eXBlIjoid2ViYXV0aG4uZ2V0IiwiY2hhbGxlbmdlIjoiSVBiTjNqSmtLZXFOaUpPZFZ4VXg2MWpfSzhUUlE4aDFFTUoxbXNYeHEyMCIsIm9yaWdpbiI6Imh0dHA6Ly9sb2NhbGhvc3Q6NjMzNDIiLCJjcm9zc09yaWdpbiI6ZmFsc2V9",
    "signature": "MEYCIQDbkTDweR2uF4Jx_p7fJO3uYJ0hu68IANSNCMhfS3HjggIhANtOQn88O9ifLxnlho-136MopTNEvMCfqtTKhkCWX2cQ",
    "userHandle": "ZG9l"
  }
}

###
